name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: '1.78'
          components: clippy
          override: true
      - name: Clippy
        run: cargo clippy -- -D warnings
      - name: Test
        run: cargo test --all --offline

  wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: '1.78'
          components: clippy
          target: wasm32-unknown-unknown
          override: true
      - name: Build (wasm)
        run: cargo build --all --target wasm32-unknown-unknown --release
